name: Build EXE with Nuitka

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install nuitka pyqt5 selenium webdriver-manager

      - name: Build the EXE with Nuitka
        run: |
          python -m nuitka --standalone --plugin-enable=pyqt5 --windows-console-mode=disable --assume-yes-for-downloads --windows-icon-from-ico=Elvui_Freebie_icon.ico --output-filename=Elvui_Freebie.exe main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Elvui_Freebie
          # Nuitka standalone builds produce a folder named Elvui_Freebie.dist
          path: main.dist
